name: "Bump Version"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Bump Version"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.email ""
          git config --global user.name "GitHub Actions Robot"
      - name: Bump Version
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
        run: |
          if [[ "$CDP_COMMIT_MESSAGE" =~ ^.*\((m|M)ajor\)\:.*$ ]]; then
            bash ./.github/scripts/bump-version.sh MAJOR "$(bash ./.github/scripts/generate-changelog.sh)"
          elif [[ "$CDP_COMMIT_MESSAGE" =~ ^.*\((m|M)inor\)\:.*$ ]]; then
            bash ./.github/scripts/bump-version.sh MINOR "$(bash ./.github/scripts/generate-changelog.sh)"
          else
            bash ./.github/scripts/bump-version.sh PATCH "$(bash ./.github/scripts/generate-changelog.sh)"
          fi
